### ISSUE TITLE
buiding on mac 

### ISSUE THREAD

**Issue by johndpope** [aykutalparslan/Ferrite#446]
not sure why - but project is not happy.
<img width="657" alt="Screen Shot 2022-08-21 at 11 17 58 pm" src="https://user-images.githubusercontent.com/289994/185792739-b6c9d662-c9d6-41af-9e16-1d27faefeace.png">

had to delete .env to get it to progress - but then...

build  9/13] COPY [Ferrite.Core/Ferrite.Core.csproj, Ferrite.Core/]                                                                                                                 0.0s
 => ERROR [build 10/13] RUN dotnet restore "Ferrite/Ferrite.csproj"                                                                                                                      3.6s
------
 > [build 10/13] RUN dotnet restore "Ferrite/Ferrite.csproj":
#0 2.129   Determining projects to restore...
#0 2.135   Skipping project "/src/Ferrite.Services/Ferrite.Services.csproj" because it was not found.
#0 3.202   Skipping project "/src/Ferrite.Services/Ferrite.Services.csproj" because it was not found.
#0 3.290   Skipping project "/src/Ferrite.Services/Ferrite.Services.csproj" because it was not found.
#0 3.346   Skipping project "/src/Ferrite.Services/Ferrite.Services.csproj" because it was not found.
#0 3.394 /usr/share/dotnet/sdk/6.0.400/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(144,5): error NETSDK1045: The current .NET SDK does not support targeting .NET 7.0.  Either target .NET 6.0 or lower, or use a version of the .NET SDK that supports .NET 7.0. [/src/Ferrite.Transport/Ferrite.Transport.csproj]
#0 3.401 /usr/share/dotnet/sdk/6.0.400/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(144,5): error NETSDK1045: The current .NET SDK does not support targeting .NET 7.0.  Either target .NET 6.0 or lower, or use a version of the .NET SDK that supports .NET 7.0. [/src/Ferrite.Crypto/Ferrite.Crypto.csproj]
#0 3.404 /usr/share/dotnet/sdk/6.0.400/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(144,5): error NETSDK1045: The current .NET SDK does not support targeting .NET 7.0.  Either target .NET 6.0 or lower, or use a version of the .NET SDK that supports .NET 7.0. [/src/Ferrite.TL/Ferrite.TL.csproj]
#0 3.412 /usr/share/dotnet/sdk/6.0.400/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(144,5): error NETSDK1045: The current .NET SDK does not support targeting .NET 7.0.  Either target .NET 6.0 or lower, or use a version of the .NET SDK that supports .NET 7.0. [/src/Ferrite.Utils/Ferrite.Utils.csproj]
#0 3.414 /usr/share/dotnet/sdk/6.0.400/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(144,5): error NETSDK1045: The current .NET SDK does not support targeting .NET 7.0.  Either target .NET 6.0 or lower, or use a version of the .NET SDK that supports .NET 7.0. [/src/Ferrite/Ferrite.csproj]
#0 3.420 /usr/share/dotnet/sdk/6.0.400/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(144,5): error NETSDK1045: The current .NET SDK does not support targeting .NET 7.0.  Either target .NET 6.0 or lower, or use a version of the .NET SDK that supports .NET 7.0. [/src/Ferrite.Data/Ferrite.Data.csproj]
#0 3.425 /usr/share/dotnet/sdk/6.0.400/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(144,5): error NETSDK1045: The current .NET SDK does not support targeting .NET 7.0.  Either target .NET 6.0 or lower, or use a version of the .NET SDK that supports .NET 7.0. [/src/Ferrite.Core/Ferrite.Core.csproj]
------
failed to solve: executor failed running [/bin/sh -c dotnet restore "Ferrite/Ferrite.csproj"]: exit code: 1

**Comment by aykutalparslan** [comment]
I myself stopped using docker compose a while ago so it might be why. I currently am using Rider on a Mac(x64). I am starting up Redis, Cassandra, MinIO and ElasticSearch then the Ferrite console app. But let me try to add some build instructions and also fix the docker build.

**Comment by aykutalparslan** [comment]
I have updated the README and removed the docker files temporarily. Will be adding docker support in the near future.

**Comment by johndpope** [comment]
the infrastructure needed to run - it makes sense to run in docker - and run the c# server on local machine.
I just installed rider - 
it seems you've invested a lot of time into this - 
how do you know which APIs 300 that are not implemented?
have you considered using something like supabase to stand on top of gotrue / auth layer - notifications / social sign ups etc? supabase is built on postgres - and postgresREST which gives you a basic CRUD out of the box that would simplify api controller development in my opinion. you can have all the logic in stored procedure - and invoke that from client using their libraries. 

is there an openapi schema - or http archive of captured traffic for telegram ? how do you know there's 300 api methods?

**Comment by aykutalparslan** [comment]
The project uses .NET 7 preview 7. Should have added that to the README too sorry. It made sense at the time because I estimated the framework will be released before the project is usable. It's a preview language feature [UTF8StringLiterals](https://github.com/dotnet/csharplang/blob/main/proposals/utf8-string-literals.md).

Regarding the other questions:
- I did indeed invested a lot of time into the project in the last 6 months but I think in another 6 months it will be worth it when I can finally deploy a usable server. I actually started building another [Telegram-Server](https://github.com/aykutalparslan/Telegram-Server) in Java back in 2015 but never got to complete it. The API varied a lot(different layers) between iOS, Android and Desktop apps back then. Now all the major apps use the same API layer with minor differences and the APIs like messages.sendMessage should not change as often.
- Telegram has -always had actually- an open [API](https://core.telegram.org/schema). You can also read the source for the apps if the documentation for the API method is ambiguous.
- Most of the API has open issues organized into milestones here. That's how I keep track and there's currently a little over 220. There were a couple of new layers of the API released since I started development so 300 is a rough estimate reflecting that. I close and issue when I've implemented that particular API method.
- Currently project has a [IKVStore](https://github.com/aykutalparslan/Ferrite/blob/master/Ferrite.Data/Repositories/IKVStore.cs) contract which is easy to add a new data stores for like [Cassandra](https://github.com/aykutalparslan/Ferrite/blob/master/Ferrite.Data/Repositories/CassandraKVStore.cs) and [RocksDB](https://github.com/aykutalparslan/Ferrite/blob/master/Ferrite.Data/Repositories/RocksDBKVStore.cs). Then it becomes trivial to create a [MessageRepository](https://github.com/aykutalparslan/Ferrite/blob/master/Ferrite.Data/Repositories/MessageRepository.cs). I am currently refactoring old code into this pattern. The reasoning behind this is comes from the scenarios I have in mind. I want to be able to deploy the project in a single container which would be possible with RocksDB, a custom in memory cache, Lucene and local file system. If someone wanted to run a service for say 100000 users then PostgreSQL or MariaDB would make sense. It would be however easier to scale IMHO if we had something like Cassandra at the persistence layer. Redis and ElasticSearch would be essential for any real world deployment. We can look at other alternatives for MinIO but most would be more complicated. 
- supabase seems cool. I'll investigate if adding it as an alternative data/object store will reduce the complexity of the aforementioned architecture.

**Comment by aykutalparslan** [comment]
Please see the updated README for a link to a modified Android App as well.

**Comment by aykutalparslan** [comment]
This infrastructure is not needed anymore. Details are in the README.
